services:
  - type: web
    name: ubuntu-ssh-render
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /
    ports:
      - 22
      - 8080
